nginx1:
  image: nginx:latest
  ports:
   - '81:80'
  volumes:
   - ./nginx:/etc/nginx/conf.d
   - ./logs/nginx:/var/log/nginx
   - ./wordpress:/var/www/html
  links:
   - wordpress
  restart: always
nginx2:
  ports:
   - '82:80'
  image: nginx:latest
  volumes:
   - ./nginx:/etc/nginx/conf.d
   - ./logs/nginx:/var/log/nginx
   - ./wordpress:/var/www/html
  links:
   - wordpress
  restart: always

mysql:
    image: mariadb
    ports:
        - '3306:3306'
    volumes:
        - ./db-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=test123
    restart: always

wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    ports:
        - '9000:9000'
    volumes:
        - ./wordpress:/var/www/html
    environment:
        - WORDPRESS_DB_NAME=wpdb
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=mysql
        - WORDPRESS_DB_PASSWORD=test123
    links:
        - mysql
    restart: always

haproxy:
  image: haproxy:1.5.18
  ports:
   - '80:80'
   - '1984:1984'
  volumes:
   - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  links:
   - nginx1
   - nginx2
